### ISSUE TITLE
Cross Compile for Linux Kernel 2.6.27

### ISSUE THREAD

**Issue by ykhui0909** [lwfinger/rtl8188eu#174]
I would like to cross compile for embedded device with linux kernel 2.6.27. I set parameters based on previous thread.

set ARCH=arm
set CROSS_COMPILE=/path/arm-linux-
make KSRC=/path/to/kernel/linux-2.6.27

I got following error when I do the cross-compilation:

make[1]: Entering directory `/path/to/test/linux-2.6.27'
  CC [M]  /path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.o
  In file included from /path/to/test/RTL8188/rtl8188eu-master/include/rtw_ht.h:24,
                   from /path/to/test/RTL8188/rtl8188eu-master/include/drv_types.h:36,
                   from /path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c:23:
/path/to/test/RTL8188/rtl8188eu-master/include/wifi.h:633: error: redefinition of ‘struct ieee80211_ht_addt_info’
/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c: In function ‘add_RATid’:
/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c:470: error: ‘struct ieee80211_ht_cap’ has no member named ‘mcs’
/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c: In function ‘rtw_check_beacon_data’:
/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c:903: error: implicit declaration of function ‘get_unaligned_le16’
/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c:1048: error: ‘struct ieee80211_ht_cap’ has no member named ‘mcs’
/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.c:1049: error: ‘struct ieee80211_ht_cap’ has no member named ‘mcs’
make[2]: *** [/path/to/test/RTL8188/rtl8188eu-master/core/rtw_ap.o] Error 1
make[1]: *** [_module_/path/to/test/RTL8188/rtl8188eu-master] Error 2
make[1]: Leaving directory `/path/to/test/linux-2.6.27.special'
make: *** [modules] Error 2

May I ask if it is possible to cross-compile on linux 2.6 target? 

Thanks so much for your kind advice.

**Comment by gcasse** [comment]
For info, this driver works successfully on 2.6.30 / armv5te.
It was compiled using:
export ARCH=arm
export CROSS_COMPILE=/path/arm-linux-
export KSRC=/path/to/kernel/linux-2.6.30
make -C $KSRC M=$PWD all

HTH
