### ISSUE TITLE
Unable to compile on OSMC

### ISSUE THREAD

**Issue by nikunjlahoti** [lwfinger/rtl8188eu#183]
My primary objective is to start Soft-AP on raspberrypi2 running osmc (kernel = 4.4.16-4-osmc). I was able to start AP in Windows using the supplied CD.

`modinfo r8188eu` suggests that the driver is in staging.
/lib/modules/4.4.16-4-osmc/kernel/drivers/staging/rtl8188eu/r8188eu.ko

`sudo ln -s /usr/src/rbp2-headers-4.4.16-4-osmc /lib/modules/4.4.16-4-osmc/build`
`sudo tar -xjvf /usr/src/rbp2-source-4.4.16-1-osmc.tar.bz2`
`sudo mv rbp2-source-4.4.16-1-osmc rbp2-source-4.4.16-4-osmc`

(adding mach/memory.h)
`sudo cp -r /usr/src/rbp2-source-4.4.16-4-osmc/arch/arm/mach-bcm2709/include/mach/ /usr/src/rbp2-headers-4.4.16-4-osmc/arch/arm/include/`

`$ make all`

> make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.4.16-4-osmc/build M=/home/osmc/rtl8188eu  modules
> make[1]: Entering directory '/usr/src/rbp2-headers-4.4.16-4-osmc'
>   CC [M]  /home/osmc/rtl8188eu/core/rtw_ap.o
>   CC [M]  /home/osmc/rtl8188eu/core/rtw_br_ext.o
> In file included from include/linux/filter.h:16:0,
>                  from include/net/sock.h:62,
>                  from include/net/inet_sock.h:27,
>                  from include/net/ip.h:30,
>                  from /home/osmc/rtl8188eu/core/rtw_br_ext.c:23:
> include/net/sch_generic.h: In function ‘skb_at_tc_ingress’:
> include/net/sch_generic.h:414:2: error: implicit declaration of function ‘G_TC_AT’ [-Werror=implicit-function-declaration]
>   return G_TC_AT(skb->tc_verd) & AT_INGRESS;
> include/net/sch_generic.h:414:33: error: ‘AT_INGRESS’ undeclared (first use in this function)
>   return G_TC_AT(skb->tc_verd) & AT_INGRESS;

I found a similar issue at https://www.open-mesh.org/issues/246.
Where the solution says "We should not compile a kernel module against kernel headers which are not meant to be used for kernel modules".

(source: https://discourse.osmc.tv/t/tutorial-compiling-a-working-kernel-driver-for-rtl8192eu/5252)

**Comment by nikunjlahoti** [comment]
I was able to easily compile it on Ubuntu 15.04 4.2.0-35-generic. After blacklisting `lsmod | grep 8188` gives correct result. 

Will check if the AP capabilities work in Ubuntu and go back to raspberry pi 2.

**Comment by nikunjlahoti** [comment]
I got it to work on Ubuntu Snappy 16.04.2! Thanks!
