### ISSUE TITLE
fails to compile on linux-4.9.16

### ISSUE THREAD

**Issue by coot** [lwfinger/rtl8188eu#208]
I got bunch of errors:
```
make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.16-gentoo/build M=/home/marcin/repos/linux/rtl8188eu  modules
make[1]: Entering directory '/usr/src/linux-4.9.16-gentoo'
  CC [M]  /home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.o
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7820:2: error: unknown field ‘private’ specified in initializer
  .private = rtw_private_handler,
  ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7820:13: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .private = rtw_private_handler,
             ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7820:13: note: (near initialization for ‘rtw_handlers_def.get_wireless_stats’)
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7821:2: error: unknown field ‘private_args’ specified in initializer
  .private_args = (struct iw_priv_args *)rtw_private_args,
  ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7821:18: warning: excess elements in struct initializer
  .private_args = (struct iw_priv_args *)rtw_private_args,
                  ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7821:18: note: (near initialization for ‘rtw_handlers_def’)
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7822:2: error: unknown field ‘num_private’ specified in initializer
  .num_private = sizeof(rtw_private_handler) / sizeof(iw_handler),
  ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7822:17: warning: excess elements in struct initializer
  .num_private = sizeof(rtw_private_handler) / sizeof(iw_handler),
                 ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7822:17: note: (near initialization for ‘rtw_handlers_def’)
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7823:2: error: unknown field ‘num_private_args’ specified in initializer
  .num_private_args = sizeof(rtw_private_args) / sizeof(struct iw_priv_args),
  ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7823:22: warning: excess elements in struct initializer
  .num_private_args = sizeof(rtw_private_args) / sizeof(struct iw_priv_args),
                      ^
/home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.c:7823:22: note: (near initialization for ‘rtw_handlers_def’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:294: /home/marcin/repos/linux/rtl8188eu/os_dep/ioctl_linux.o] Error 1
make[1]: *** [Makefile:1490: _module_/home/marcin/repos/linux/rtl8188eu] Error 2
make[1]: Leaving directory '/usr/src/linux-4.9.16-gentoo'
make: *** [Makefile:151: modules] Error 2
```

**Comment by coot** [comment]
Seems that I was just missing `CONFIG_WEXT_PRIV` in the kernel config.  Now the driver compiles, but it does not connect to internet.  The kernel logs contain:
```
[    6.984088] IPv6: ADDRCONF(NETDEV_UP): wlp0s20u4: link is not ready
[    6.986234] R8188EU: ERROR indicate disassoc
```
I tried both the driver shipped with kernel-4.9.16 (in the staging area) and one build from the master branch.
