### ISSUE TITLE
error: macro "__DATE__" might prevent reproducible builds

### ISSUE THREAD

**Issue by hardywu** [lwfinger/rtl8188eu#63]
I was trying to compile on arch linux with linux 3.15.5-1

``` bash
/home/user/Downloads/rtl8188eu/os_dep/usb_intf.c: In function ‘rtw_drv_entry’:
/home/user/Downloads/rtl8188eu/os_dep/usb_intf.c:869:51: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
  DBG_88E("build time: %s %s\n", __DATE__, __TIME__);
                                                   ^
/home/user/Downloads/rtl8188eu/os_dep/usb_intf.c:869:1: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  DBG_88E("build time: %s %s\n", __DATE__, __TIME__);
 ^
cc1: some warnings being treated as errors
scripts/Makefile.build:318: recipe for target '/home/user/Downloads/rtl8188eu/os_dep/usb_intf.o' failed
make[2]: *** [/home/user/Downloads/rtl8188eu/os_dep/usb_intf.o] Error 1
Makefile:1310: recipe for target '_module_/home/user/Downloads/rtl8188eu' failed
make[1]: *** [_module_/home/user/Downloads/rtl8188eu] Error 2
make[1]: Leaving directory '/usr/lib/modules/3.15.5-1-ARCH/build'
Makefile:146: recipe for target 'modules' failed
make: *** [modules] Error 2

```
